# Generated by Django 5.2.14 on 2026-05-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('telefono', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField()),
                ('presencial', models.BooleanField(default=True)),
                ('estado_entrega', models.TextField(default='pendiente')),
            ],
            options={
                'db_table': 'entrega',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('categoria', models.CharField(default='General', max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('metodo_pago', models.TextField()),
                ('estado_pago', models.TextField(default='pendiente')),
                ('id_entrega', models.OneToOneField(blank=True, db_column='id_entrega', null=True, on_delete=django.db.models.deletion.SET_NULL, to='LibreriaChichi.entrega')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('estado_pedido', models.TextField(default='pendiente')),
                ('fecha_entrega_acordada', models.DateField(blank=True, null=True)),
                ('tipo_pedido', models.TextField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.RESTRICT, to='LibreriaChichi.cliente')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.AddField(
            model_name='entrega',
            name='id_pedido',
            field=models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='LibreriaChichi.pedido'),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='LibreriaChichi.pedido')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.RESTRICT, to='LibreriaChichi.producto')),
            ],
            options={
                'db_table': 'detallepedido',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_producto', models.OneToOneField(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='LibreriaChichi.producto')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
