# Generated by Django 5.2.15 on 2026-06-17 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreriaChichi', '0003_producto_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(db_index=True, max_length=64, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clave API',
                'verbose_name_plural': 'Claves API',
                'db_table': 'clave_api',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id_transferencia', models.AutoField(primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=80)),
                ('numero_operacion', models.CharField(max_length=60)),
                ('rut_pagador', models.CharField(max_length=12)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_transferencia', models.DateField()),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='transferencias/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de validación'), ('validada', 'Validada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=12)),
                ('coincide_monto', models.BooleanField(default=False)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('id_pago', models.OneToOneField(blank=True, db_column='id_pago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='LibreriaChichi.pago')),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='LibreriaChichi.pedido')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_validadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transferencia',
                'ordering': ['-creado'],
                'permissions': [('validar_transferencia', 'Puede validar transferencias bancarias')],
                'unique_together': {('banco', 'numero_operacion')},
            },
        ),
    ]
